### ISSUE TITLE
TRATTAMENTO SUPERFICIALE LAME COMM. 126.22

### ISSUE THREAD

**Issue by nbianchinewmascherpa** [nbianchinewmascherpa/Non-conformit-#10]
le lame del sezionatore campione erano trattate (nichelate o argentate?).
sono state fornite lame rame non trattate.

Il cliente ha sollevato il problema.
rispedirà i sezionatori.

@ELEONORANEW 
sentire Lucini per capire se spediscono loro o dobbiamo ritirare noi

@annalisa2023 
riesci a farti fare un preventivo per l'argentatura a 12 micron per i disegni (li trovi in: Z:\COMMERCIALE\CONFERMA D'ORDINE\2022\126.22 E-DISTRIBUZIONE\126.22 - DISEGNI PRODUZIONE)
E10138 n. 9 pz
E10139 n. 9 pz
E10142 n. 18 pz

@efagnani 
mandare extra-costo per trattamento

**Comment by ELEONORANEW** [comment]
22/02/2023: Chiamato Lucini.
Ha parlato con il suo capo Micheli.
Vogliono offerta sia per trattamento argentatura, sia per trattamento nichelatura.
Ci daranno i 3 sezionatori montati. Quindi dobbiamo considerare smontaggio - montaggio - regolazione - collaudo.
Ha chiesto di aggiungere nell'offerta anche la voce per il trasporto (ritiro e consegna). Poi valuteranno se consegnarceli loro o se fare noi entrambi i trasporti.
