### ISSUE TITLE
MONTAGGIO ISOLATORE SEZ. EM242 COMM. 138.22

### ISSUE THREAD

**Issue by nbianchinewmascherpa** [nbianchinewmascherpa/Non-conformit-#15]

**Comment by nbianchinewmascherpa** [comment]
DESCRIZIONE NC: 
sui sezionatori EM 242 sono stati montati:
n. 1 isolatore centrale 
n. 1 isolatore laterale 
al contrario

CAUSA:
distrazione operatore?
mancato CQ?

RISOLUZIONE:
smontaggio e rimontaggio dei due isolatori nella posizione corretta.

**Comment by nbianchinewmascherpa** [comment]
MATERIALE: fotografie NC salvata nella cartellina della NC 13.23

**Comment by ELEONORANEW** [comment]
16/03/2023
Gli isolatori sono stati smontati e rimontati nella posizione corretta.
Su entrambi i poli revisionati, sono state effettuate nuovamente le regolazioni e le prove di resistenza

**Comment by nbianchinewmascherpa** [comment]
TEMPO: 4H 120€
