### ISSUE TITLE
SALDATURA DIS. S10052

### ISSUE THREAD

**Issue by nbianchinewmascherpa** [nbianchinewmascherpa/Non-conformit-#16]
DESCRIZIONE NC:
errato processo di saldatura. la barra filettata è storta.

CAUSA:
la saldatura doveva essere realizzata saldando prima la barra filettata e poi il bicchiere. A disegno non è indicata nessuna procedura di saldatura. 
in fase di progettazione, se viene identificata in fase di progettazione una procedura di saldatura, è FONDAMENTALE indicarla a disegno.

RISOLUZIONE:
si cerca di recuperare il particolare raddrizzando la barra filettata.
![IMG-20230316-WA0004](https://user-images.githubusercontent.com/115451135/225848259-a0c5de0b-118e-49ec-87d7-7725f1bcf1dd.jpg)

**Comment by ELEONORANEW** [comment]
20/03/2023 - Alessandrini ha emesso dis. S10052 in rev. 1.
Sul disegno sono state aggiunte le procedure di composizione.

**Comment by nbianchinewmascherpa** [comment]
chiusura: sistemato in fase di montaggio. costo NC 50€ gestione + produzione
