### ISSUE TITLE
GRUPPO MICRO S10071 - PIASTRA DIS. S10071_A

### ISSUE THREAD

**Issue by nbianchinewmascherpa** [nbianchinewmascherpa/Non-conformit-#18]
DESCRIZIONE NC:
la piastra superiore fissaggio gruppo micro è stata disegnata senza considerare la posizione delle forature di fissaggio e ingombro della bulloneria con le alette dei micro. risultava impossibile il collegamento dei micro

CAUSA: mancata valutazione delle interferenze in sede progettuale

RISOLUZIONE:
utilizzate n. 4 piastre dis. U171_A e fissato il gruppo micro con le forature sull'asse orizzontale del riduttore
![WhatsApp Image 2023-03-20 at 14 54 51](https://user-images.githubusercontent.com/115451135/226370911-1e1a5825-1d99-4ed6-afcb-c8fa7de6e750.jpeg)
![WhatsApp Image 2023-03-20 at 14 54 51 (1)](https://user-images.githubusercontent.com/115451135/226370915-848a6640-404e-49da-839c-be5238ec02a5.jpeg)

@ELEONORANEW  per favore aggiornare distinta cambiando il codice. 
R. ALESSANDRINI: aggiornare disegno di assieme S10071 e disegno di assieme montaggio

COSTO NC:
50€ operaio per risoluzione
30€ costo materiale da scartare
25€ gestione

**Comment by ELEONORANEW** [comment]
Distinta modificata in data 20/03/2023
