### ISSUE TITLE
PARTICOLARE O10350_A

### ISSUE THREAD

**Issue by ELEONORANEW** [nbianchinewmascherpa/Non-conformit-#19]
particolari sono stati tagliati dalla SEIT - RIF. ORDINE 140/23
sul particolare 1 del disegno O10350_A la foratura è stata realizzata una foratura d 45 anzichè 55mm

![image](https://user-images.githubusercontent.com/122519843/226933994-9d074552-a151-4867-b4d7-9966d691df98.png)

Causa: il fornitore ha sbagliato nella lettura del disegno.

Soluzione: il fornitore ritaglia i nuovi pezzi.
Per il particolare già saldato da Seit, tagliamo il pezzo del piatto con il foro da 45mm e sormontiamo il nuovo piatto con il foro d 55.

**Comment by nbianchinewmascherpa** [comment]
CHIUSURA:
il fornitore ha ritagliato i particolari senza costi aggiuntivi.
Costo di gestione: 50 € michele (viaggi consegna/ritiro) + 25 € gestione interna + 25€ sistemazione primo particolare fornito saldato.
i particolari NC rimasti come rottame.
