### ISSUE TITLE
CABLAGGIO PIASTRA

### ISSUE THREAD

**Issue by ELEONORANEW** [nbianchinewmascherpa/Non-conformit-#21]
JOB 138/23
Il cablaggio della piastra non è conforme.
I morsetti toccano il fondo della cassetta. 

![image](https://user-images.githubusercontent.com/122519843/226964855-96909df6-4e47-4a76-ab72-8ddc1776e760.png)

Causa: mancanza di comunicazione tra reparto elettrico (Tiberto) e progettista meccanico (AR)

Soluzione: Modificare l’orientamento della morsettiera (ruotare di 180°). - Cristian Ferro
Ruotando la posizione dei morsetti, questi risultano essere vicini alla canalina.
E’ necessario spostare la canalina un centimetro sopra e di conseguenza anche il termostato.

**Comment by nbianchinewmascherpa** [comment]
chiusura: ruotati i morsetti di 180°. tempo di rilavorazione 1h. 
costo NC 50 €
