### ISSUE TITLE
MANCANZA DI UN PANNELLO INTERNO

### ISSUE THREAD

**Issue by ELEONORANEW** [nbianchinewmascherpa/Non-conformit-#23]
JOB 138/22
Sul disegno della cassetta non sono stati indicati i fori per i pulsanti della bobina.
Ma dove sono stati previsti?
Se i pulsanti li metto sullo sportello esterno della cassetta, come faccio a schiacciare il pulsante della bobina e poi tirare la levetta pelo sblocco inserimento manovella?
Dovrei aprire lo sportello per fare questa operazione MA NON E' STATO PREVISTO UN PANNELLO INTERNO necessario secondo norma per schermare tutti gli ingranaggi (sono presenti barre filettate per il finecorsa)
![image](https://user-images.githubusercontent.com/122519843/226966690-bb80a5fa-89e9-4e17-9854-6e77b1a10206.png)

Causa: non considerati i pulsanti e un pannello interno in fase di progettazione (AR)

Soluzione: realizzato un carter interno per schermare i finecorsa meccanici e per fissare i pulsanti delle bobine
![image](https://user-images.githubusercontent.com/122519843/226967067-bb420d56-595b-476a-93b3-52a3ad0bf9cb.png)

**Comment by ELEONORANEW** [comment]
Realizzato disegno S10082 - carter protezione e aggiornata distinta aggiungendo anche la viteria necessaria per il fissaggio del carter

**Comment by nbianchinewmascherpa** [comment]
75€
