### ISSUE TITLE
GIUNTO LINEA dis. S10062

### ISSUE THREAD

**Issue by ELEONORANEW** [nbianchinewmascherpa/Non-conformit-#24]
job 138/22
Il fornitore ha realizzato 4 piastre dis. S10058_A.
Pertanto il giunto linea è stato saldato con il disco S10058_A e non il disco S10062_A.
I dischi S10058 e S10062 non ruotano e non c'è un fermo in apertura sia per la linea, sia per la terra.

![image](https://user-images.githubusercontent.com/122519843/226968120-5302237a-ebd9-4e9a-a0f0-bdd4a24fede5.png)

Causa: in fase di ordine è stato mandato solo il dis. S10058_A

Soluzione: tagliata la parte eccedente sul disco di linea. I dischi linea e terra ruotano, c'è un fermo anche in aperto sia per la linea, sia per la terra.
Problema: il foro per il perno del blocco a chiave è troppo largo (foro d 18 per un perno d 12) e questo comporta dei giochi sia sulla linea, sia sulla terra
![image](https://user-images.githubusercontent.com/122519843/226968766-2f647a95-6796-4100-8c3b-8b7ccc95f1e8.png)

**Comment by nbianchinewmascherpa** [comment]
CHIUSURA: modificato il disco di linea per garantire l'interblocco.
Costo NC 50 €
