### ISSUE TITLE
MICRO PER SPIA LUMINOSA - QUESTA ASSENTE SULLO SCHEMA ELETTRICO

### ISSUE THREAD

**Issue by ELEONORANEW** [nbianchinewmascherpa/Non-conformit-#25]
job 138/22

In corrispondenza della leva inserimento manovella è stato previsto un micro per segnalazione spia luminosa inserimento manovella 
ma nello schema elettrico SC10022 (approvato dal cliente) non è presente alcuna spia luminosa.

![image](https://user-images.githubusercontent.com/122519843/226970657-b86a6613-f783-407c-9822-395a4aa33d6e.png)
![image](https://user-images.githubusercontent.com/122519843/226970128-c37e2899-69de-4552-ac00-029f8ece394e.png)
![image](https://user-images.githubusercontent.com/122519843/226970464-18433749-b17b-478f-87fc-4f77f71f3a25.png)

Causa: mancanza di comunicazione tra elettrico (Tiberto) e progettista meccanico (AR)

Soluzione:
- togliere lo switch dalla cassetta
- togliere lo switch dal disegno di assieme e emettere revisione

**Comment by nbianchinewmascherpa** [comment]
RISOLUZIONE: tolto lo switch dalle cassette. lasciamo la predisposizione per il micro per la versione in cui viene richiesta la segnalazione luminosa.
