### ISSUE TITLE
TUBO MENSOLA RINVIO COMANDO DIS. O10357_A

### ISSUE THREAD

**Issue by nbianchinewmascherpa** [nbianchinewmascherpa/Non-conformit-#27]
DESCRIZIONE NC: non è stata rispettata la quota da 75mm.
CAUSA: errata lavorazione da parte del fornitore

Risoluzione: rilavorati i fori internamente per permettere il montaggio. 
tempo operatore 1 ora.

si chiede al fornitore di scontare €55 per la rilavorazione.

**Comment by annalisa2023** [comment]
Importo stornato su fatt. 30 del 31/03/23
