### ISSUE TITLE
FERMO BLOCCO TERRE SUPERIORI - COMM. 15.23

### ISSUE THREAD

**Issue by nbianchinewmascherpa** [nbianchinewmascherpa/Non-conformit-#30]
DESCRIZIONE NC:
in fase progettuale è stato pensato un piatto saldato sull'albero di terra, per il blocco delle terre superiori.
l'albero, avendo saldato da un lato il piatto e dall'altro il coltello non può essere inserito nel telaio.

CAUSA:
progettazione frettolosa?
progettazione senza 3d e verifica delle interferenze?

RISOLUZIONE:
tagliare la leva dall'albero e saldarla su un mozzo che verrà poi accoppiato all'albero con una spina.
@ELEONORANEW emettere disegni revisionati
![WhatsApp Image 2023-03-29 at 16 54 33](https://user-images.githubusercontent.com/115451135/228579571-fd579650-96e0-44af-9260-a720c2c344fe.jpeg)
![WhatsApp Image 2023-03-29 at 16 54 33 (1)](https://user-images.githubusercontent.com/115451135/228579597-2d097844-a3cc-4a10-8ddc-566af1a453e1.jpeg)

**Comment by efagnani** [comment]
Credo che anche qui serva un'azione della qualità di progettazione e secondo me è che ogni disegno del progettista in 2d DEVE passare dal 3D o meglio da solidworks animato. In sintesi tutti i disegni di Roberto devono passare da Shiva  o chi  per lui). Se no corriamo prima e perdiamo tempo dopo.

**Comment by ELEONORANEW** [comment]
Il 3D era stato creato. 
Questo è un stato un problema di distrazione sia di chi ha disegnato il pezzo in 2D sia mio che l'ho riportato in 3D, che ho semplicemente preso il disegno 2D di Roberto e copiato in 3D.
In questo caso non si tratta di un interferenza in fase di movimento che si poteva verificare con un'animazione in solidwork perchè l'animazione viene realizzata per movimentare i pezzi non per assemblare un apparecchiatura.

**Comment by ELEONORANEW** [comment]
Creato nuovo dis. C10332_D: leva C10332_A saldata su un mozzo in tubo Fe d 38x25 L=48 che poi sarà spinato sull'albero di terra al montaggio con n. 1 spina elastica inox 8X40.

Modificati di conseguenza i disegni:
B1112 - rev. 1
C10332 - rev. 2
C10334 - rev. 1

**Comment by efagnani** [comment]
Cosa si può fare per evitare l'errore di distrazione che é umano? Che controllo ci può essere?

 




 
 
NEW MASCHERPA SRL 

via Meucci 13, 20060 Pozzo d'Adda (MI) 
Tel. 0290960952 - +39 392 938 3295
***@***.***

www.newmascherpa.it 
 

Informativa Privacy - Ai sensi del D. Lgs n. 196/2003 (Codice Privacy) si precisa che le informazioni contenute in questo messaggio sono riservate e ad uso esclusivo del destinatario. Qualora il messaggio in parola Le fosse pervenuto per errore, La preghiamo di eliminarlo senza copiarlo e di non inoltrarlo a terzi, dandocene gentilmente comunicazione. Grazie. 
Privacy Information - This message, for the D. Lgs n. 196/2003 (Privacy Code), may contain confidential and/or privileged information. If you are not the addressee or authorized to receive this for the addressee, you must not use, copy, disclose or take any action based on this message or any information herein. If you have received this message in error, please advise the sender immediately by reply e-mail and delete this message. Thank you for your cooperation. 






Da: "ELEONORANEW" ***@***.***
A: "nbianchinewmascherpa/Non-conformit-" ***@***.***
Cc: "efagnani" ***@***.***,"Assign" ***@***.***
Data: Wed, 29 Mar 2023 22:43:30 -0700
Oggetto: Re: [nbianchinewmascherpa/Non-conformit-] 28.23 FERMO BLOCCO TERRE SUPERIORI - COMM. 15.23 (Issue #30)


Il 3D era stato creato.
Questo è un stato un problema di distrazione sia di chi ha disegnato il pezzo in 2D sia mio che l'ho riportato in 3D, che ho semplicemente preso il disegno 2D di Roberto e copiato in 3D.
In questo caso non si tratta di un interferenza in fase di movimento che si poteva verificare con un'animazione in solidwork perchè l'animazione viene realizzata per movimentare i pezzi non per assemblare un apparecchiatura.

**Comment by nbianchinewmascherpa** [comment]
Costo NC: 50€ gestione e progettazione.
materiale: 15 € materiale

costo NC totale: 65€
