### ISSUE TITLE
 JOB OFF.76.23

### ISSUE THREAD

**Issue by annalisa2023** [nbianchinewmascherpa/Non-conformit-#35]
contatti mobili dis. 56832_69,9
Rif.ord. Tekne 205.23
Riscontrate n. 24 pz anzichè 25 pz come indicato in ddt 157 del 31/03/23
Riscontrate n. 7 fusioni uccise 
Sulle restanti 17 fusioni Il diametro del foro è stato eseguito da M8 anzichè da M10

**Comment by nbianchinewmascherpa** [comment]
spedite a metalleghe 12 fusioni da riprendere con riporto. rif. DDT 148 del 27/04/2023. reso come materiale riparato.

**Comment by nbianchinewmascherpa** [comment]
in data 17/07/2023 è stata inviata mail di sollecito a tekne, chiedendo uno sconto pari a 60€+186€.

**Comment by nbianchinewmascherpa** [comment]
fusioni rovinate, riprese da metalleghe in c/garanzia,
chiusa NC in data 20/03/2024
