### ISSUE TITLE
ALBERO EUI596/03

### ISSUE THREAD

**Issue by ELEONORANEW** [nbianchinewmascherpa/Non-conformit-#36]
JOB 35/23
Albero comando dis. EUI596/03 - n.2 pezzi

NC: saldatura non conforme. Le leve e il bilanciere non sono saldati come da disegno.

CAUSA: non è stata utilizzata la dima di saldatura corretta

RISOLUZIONE:
- scartare n. 2 alberi realizzati da Sirtori (4 h per realizzazione 2 pz + materiale)
- realizzati n.2 nuovi kit alberi comando e portati a TSM per saldatura (5 minuti/pz per taglio + materiale + costo saldatura TSM)

**Comment by nbianchinewmascherpa** [comment]
costo NC:
- 100 € lavorazione
- 20 € saldatura TSM nuovi alberi
- 25€ ferro + 30€ laser + 30€ zincatura
- 25€ trasporti interni

totale NC: 220€
