### ISSUE TITLE
NC Comando Paracca Givodano CO 27.21

### ISSUE THREAD

**Issue by efagnani** [nbianchinewmascherpa/Non-conformit-#37]
Givodano lamenta che il tappo del comando in alluminio non si apre più.
NC da risolvere chiamandolo (ufficio tecnico) per verificare come sostituirlo. Eleonora.
Verificare esistenza della resistenza. Givodano dice che non è posizionata bene. **Deve essere sempre messa dove ci sono i micro non dove c'è la morsettiera.**
Inoltre ci sono dei dadi che devono essere lasciati lenti se no la paratia. Non è accettabile meccanicamente.
AZIONE DELLA QUALITA': i tappi in alluminio così come in inox danno problemi nel tempo verificare con Roberto Alessandrini.

**Comment by ELEONORANEW** [comment]
RISPOSTE DI ALESSANDRINI - 26/04/2023 (e-mail)
Ritengo il difetto imputabile all'esemplare in questione.
I tappi provenienti da fornitori esterni in quale lega di alluminio saranno stati realizzati?
Anche Eltom li realizza in lega di Al.

Si può valutare di passare ad un passo di filettatura 4mm, non andrei oltre per evitare allentamenti spontanei che si potrebbero verificare con le dilatazioni termiche. In questo caso bisogna verificare bene il profilo anche in funzione dell'utilizzo di utensili comuni e non speciali. In ogni caso, passo 3 o 4 mm bisogna rispettare le tolleranze delle filettature ISO.

**Comment by nbianchinewmascherpa** [comment]
chiuso in data 06/11/2023. si veda reclamo cliente ENL04_23
