### ISSUE TITLE
BARRE AL 120X12 TR - RIF. ORDINE PROFITAL 289.23

### ISSUE THREAD

**Issue by nbianchinewmascherpa** [nbianchinewmascherpa/Non-conformit-#39]
DESCRIZIONE NC:
sono state ordinate 8 barre piatto al 120x12 senza specificare SV.
confermate e consegnate le barre dal fornitore TR.

accettate dal punto di vista dimensionale, ma in fa se di lavorazione hanno presentato dei difetti di spanciamento.
tagliati 48 pezzi (3 barre)

![WhatsApp Image 2023-05-10 at 09 28 50](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/115451135/77034b99-6a2e-4702-90d5-e3bc95fc6cb9)
![WhatsApp Image 2023-05-10 at 09 28 50 (2)](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/115451135/a35cac1b-2934-4f55-8657-8e517f0361e3)
![WhatsApp Image 2023-05-10 at 09 28 50 (1)](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/115451135/98cefce9-247e-4acd-ad44-67f26e1f30da)

**Comment by nbianchinewmascherpa** [comment]
RISOLUZIONE NC:
@annalisa2023  modificare descrizione codice in namirial e aggiungere S.V. 
inviare NC al fornitore, chiedendo il reso delle 5 barre e lo sconto per le 3 barre.
Cercare ed acquistare con massima urgenza n. 8 barre 120x12 SV

**Comment by nbianchinewmascherpa** [comment]
@ELEONORANEW  bloccare produzione pezzi e segnalare i 48 particolari tagliati come NC
Se dovesse ricapitare che viene fornito TR invece dello SV, per qualsiasi materiale, fare una prova su un pezzo (taglio + forature), prima di iniziare la produzione del lotto.

**Comment by ELEONORANEW** [comment]
Produzione bloccata.
Rimessa nuova bolla per la realizzazione dei primi 29 pezzi con piatto 120x12 S.V. disponibile a magazzino.
E' necessario acquistare al più presto il materiale per completare il lotto.

I pezzi NON conformi sono stati messi in una scatola e applicato il cartello NC

**Comment by nbianchinewmascherpa** [comment]
Rese n.5 barre TR al fornitore con DDT 293 del 17/07/2023.
costo NC: 358.72€ + 25 gestione = 383.72€
