### ISSUE TITLE
NON CONFORMITA' U063_I - BOLLA 23/476

### ISSUE THREAD

**Issue by ELEONORANEW** [nbianchinewmascherpa/Non-conformit-#46]
I particolari dis. U063_I sono stati realizzati in ferro e non in inox come indicato su disegno.

Anche il controllo qualità non ha verificato la correttezza del materiale.

Cause:
disattenzione da parte di chi ha realizzato i pezzi (Ferro) e ci chi li ha controllati (Barzaghi)
Tempo totale lavorazione + controllo: 24m 3s

Cosa fare: emessa nuova bolla di lavorazione n.23/538 per realizzazione altri pezzi in inox

![image](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/122519843/d16af8f7-b578-4187-835f-299c08658f50)

**Comment by nbianchinewmascherpa** [comment]
costo NC:
costo pezzi NC in ferro: 10€ lavorazione + 6 € materiale
Costo rilavorazione: 15€
