### ISSUE TITLE
TARGHE BACEDO COMM.90.91.92 AT

### ISSUE THREAD

**Issue by annalisa2023** [nbianchinewmascherpa/Non-conformit-#5]
Rif. ddt Bacedo n.   ns. ord. 498/22 

Tutte le targhe sono state prodotte con anno 2022 nel codice a Barre. 
Una è stata riprodotta doppia , e una è mancante.

RISOLUZIONE: richiesta nuova riproduzione

**Comment by nbianchinewmascherpa** [comment]
targhe rifatte dal fornitore senza costi aggiuntivi.
