### ISSUE TITLE
job 65/23 - HIPE - dis. 0000600

### ISSUE THREAD

**Issue by ELEONORANEW** [nbianchinewmascherpa/Non-conformit-#51]
NON CONFORMITA' RISCONTRATE DAL CLIENTE - email del 27/07/2023
a)	ampiezza del supporto 173 risulta variabile tra circa 177 e 174,5. I 2 lembi del presso-piegato non sono paralleli e lo scostamento dimensionale è eccessivo ai fini dell’impiego da noi previsto. I segni di lavorazione con asportazione di truciolo a Ra 3,2 all’esterno dei due piani implicano che l’esterno dei 2 piani del supporto, su necessità, deve essere ripreso mediante fresatura al fine di garantire l’ampiezza 173 ed il parallelismo (si possono ritenere accettabili entro tolleranza dell’ordine di 0,5 mm). È evidente sul componente che questa operazione è stata omessa
b)	le 2 asolature “orizzontali” in coord. B/8-9, realizzate prima della piegatura, sono state deformate per effetto della piegatura stessa in modo eccessivo; dal lato interno l’ampiezza nominale 12 è ridotta a circa 9,6 e interferisce perciò con il montaggio di bulloneria M10
c)	le 4 asolature “orizzontali” in coord. B-C/1-3 sono state lavorate erroneamente ad ampiezza R6 (come le 4 asole “verticali contrapposte) anziché R7; la minorazione dell’ampiezza a circa 11,5 dovuta al rivestimento galvanico interferisce con il montaggio di bulloneria M12

Allegata copia del disegno con annotazioni e documentazione fotografica.
Il cliente scrive:
il componente vi sarà reso per la necessaria ripresa mediante lavorazione meccanica per la risoluzione delle problematiche sopra elencate, come di seguito ipotizzato:
1)	fresatura dei 2 piani esterni per garantire quota 173 e parallelismo entro tolleranza indicata al punto a). È ammissibile la locale riduzione dello spessore del presso-piegato al di sotto della quota minima 14 indicata a disegno indicativamente entro 0,5 mm di tolleranza
2)	ripresa delle 2 asolature orizzontali strette dalla piegatura del piatto
3)	ripresa delle 4 asole orizzontali per ampliamento a R7
4)	ri-zincatura a caldo del supporto dopo lavorazioni di sistemazione (il rivestimento con semplice zinco spray non garantisce sufficiente protezione a causa dello spessore esiguo).
![0000600_Mascherpa](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/122519843/373d4b64-382c-4b68-bf93-1ed2b2fd1764)

@annalisa2023: inviare non conformità al fornitore (Seit)
@annalisa2023: coordinarsi con cliente per reso materiale (hanno scritto che spediscono loro)

**Comment by nbianchinewmascherpa** [comment]
- particolare 0000600 scontato da seit a compensazione dei DDT 309-315.
- Riprodotto particolare con ordine 590.23 cmc - 80€ 
- lavorazione interna 25€ + zincatura e logistica 15€

rispedito particolare rifatto al cliente in data 05/10/2023 ddt 458
