### ISSUE TITLE
job 61/23 - dis. K10433 - ordine n. 501 Tekne

### ISSUE THREAD

**Issue by ELEONORANEW** [nbianchinewmascherpa/Non-conformit-#52]
ordine n. 501 Tekne - dis. K10433

NON CONFORMITA': la fresatura è stata realizzata dalla parte opposta rispetto al disegno.

@annalisa2023 : inviare non conformità a Tekne
Ho già sentito Siena, ha detto che stanno già provvedendo a recuperare il materiale per realizzare nuovi pezzi.

![IMG-20230728-WA0002](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/122519843/5a06d052-c70c-42f7-8e64-7c20d433762d)

**Comment by nbianchinewmascherpa** [comment]
riconsegnati pezzi NC rilavorati con ddt 393 del 31/07/2023.
