### ISSUE TITLE
job 43/23 + 70/23 + 71/23 - ordine n. 534/23 - Tekne - dis. O10188_D - q.tà inferiore rispetto all'ordine

### ISSUE THREAD

**Issue by ELEONORANEW** [nbianchinewmascherpa/Non-conformit-#53]
Ordine n. 534/23 Tekne - dis. O10188_D - q.tà inferiore rispetto all'ordine

Sono stati ordinati 40 pezzi, ma Tekne è riuscita a realizzare solo 33 pezzi.
A Tekne è stata spedita una barra lunga 6m (avrebbero cmq potuto realizzare 39 pezzi considerando uno scarto di lavorazione di 5mm)

Causa: Tekne ha avuto maggiore scarto di lavorazione rispetto ai 5mm soliti considerati.

Azioni:
@annalisa2023: chiamare Tekne. Servono ancora 3 pezzi per completare le ns. commesse  in essere
@annalisa2023: se dobbiamo fornire il materiale per la lavorazione, chiedere sempre a chi ci lavora i pezzi quanto scarto di lavorazione deve essere considerato.

**Comment by annalisa2023** [comment]
inviata mail a Tekne. Riprodurranno i pezzi utilizzando tubo fe con diam.int. 80

**Comment by nbianchinewmascherpa** [comment]
pezzi mancanti consegnati con DDT 400 del 03/08/2023 - rif. protocollo FT 697.
Particolari mancanti realizzati a 21.8€/cad invece che 10,80€/cad. consegnati 11 pezzi

Costo NC:
121 € di extra
23.8 € di trasporto

totale: 144.83€
