### ISSUE TITLE
job 43/23 + 70/23 + 71/23 - ddt 1493 - CMC - dis. O10194_A1

### ISSUE THREAD

**Issue by ELEONORANEW** [nbianchinewmascherpa/Non-conformit-#54]
ddt 1493 - CMC 

Sul ddt sono indicati 48 pezzi, ma ne sono stati consegnati solo 23.

@annalisa2023: chiamare CMC per capire dove sono finiti gli altri 25 pezzi mancanti
@annalisa2023: quando arrivano i pezzi mancanti, portare n.1 pezzo dis. O10194_A1 a TSM.

**Comment by annalisa2023** [comment]
Chiamato CMC. Hanno erroneamente consegnato solo una scatola anzichè due a DHL. Procediamo con il ritiro della seconda scatola e ci sconteranno il costo di Euro 35,00 per il doppio ritiro.

**Comment by nbianchinewmascherpa** [comment]
scontati 35€ per la gestione del trasporto - protocollo FT 622.
