### ISSUE TITLE
job 70/23 + 71/23 - dis. U054 - ordine SEIT 470/23

### ISSUE THREAD

**Issue by ELEONORANEW** [nbianchinewmascherpa/Non-conformit-#55]
dis. U054 - ordine SEIT 470/23

NON CONFORMITA': errata piega rispetto al disegno

@annalisa2023 : inviare non conformità al fornitore
I pezzi saranno rilavorati internamente da Paolo Barzaghi e comunicherà tempo impiegato ad @annalisa2023 per addebito costo lavoro a fornitore.

![IMG-20230731-WA0006](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/122519843/8e638e9c-f64e-47ae-bbab-fbe771c55981)

**Comment by nbianchinewmascherpa** [comment]
applicato sconto in FT per le NC riscontrate.
rif. protocollo fattura 626.
