### ISSUE TITLE
Tubo tondo FE z/n 1 pollice  - Poletti comm. 96.22

### ISSUE THREAD

**Issue by annalisa2023** [nbianchinewmascherpa/Non-conformit-#6]
Rif. ns ord. 40.23 rev.1  

Il materiale consegnato risulta di sp. 3 mm anziche 2,65 come specificato nell'ordine.  
Il fornitore non accetta la non conformità in quanto sostiene che sui tubi carpenteria c'è una tolleranza.

**Comment by nbianchinewmascherpa** [comment]
Chiusura:
accettiamo di tenere il materiale, porre attenzione durante le lavorazioni. 
segnalare il materiale indicando lo spessore del tubo.

tenere in nota acq. materiale con spessore corretto.
