### ISSUE TITLE
G10296-G10298-G10299 - TSM 722.23

### ISSUE THREAD

**Issue by nbianchinewmascherpa** [nbianchinewmascherpa/Non-conformit-#61]
descrizione NC: in fase di saldatura sono stati saldati invertiti i collari. I collari saldati sui particolari G10298-G10299 sono stati saldati sulle piastre G10296 (e viceversa).

causa: il saldatore non ha fatto caso alla differenza tra i due collari. Materiale in c/lavorazione  non segnalato in maniera adeguata.

Risoluzione:
inviare NC al fornitore. Rispedire i pezzi con i nuovi collari da saldare.

**Comment by annalisa2023** [comment]
Rispediti i pezzi (ddt 480)

Inviata nc al fornitore. 
Richiesto costo di gestione  Euro 150,00
pari a 6 ore totali (3h. x due operatori).

**Comment by nbianchinewmascherpa** [comment]
applicato sconto sulla fattura di dicembre 2023. (FT 153)
