### ISSUE TITLE
TELAIO EUI595/01 - TSM ORDINE 742.23 - COMM. 115.23

### ISSUE THREAD

**Issue by nbianchinewmascherpa** [nbianchinewmascherpa/Non-conformit-#62]
Descrizione: il golfare dis. EUI595_01_D, è stato saldato superiormente al longherone, invece che sulla faccia inferiore. la NC non è stata riscontrata in fase di CQ, mandando avanti il particolare fino al montaggio.
Problematica in fase di montaggio, perchè l'isolatore non può essere fissato al longherone (non ha il piano di appoggio). 

Causa: distrazione del saldatore? Mancato controllo qualità.

Risoluzione:
@annalisa2023 inviare NC al fornitore
@nbianchinewmascherpa verificare con CQ le procedure per il controllo.
@ELEONORANEW  verificare possibilità di recuperare spessorando gli isolatori.

![WhatsApp Image 2023-10-20 at 10 05 01](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/115451135/ca5ecaa2-e606-4934-a001-018f8dce0ea2)
![WhatsApp Image 2023-10-20 at 10 05 01 (1)](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/115451135/e3d8b279-826a-4cc5-ae78-8395653c7a02)

**Comment by annalisa2023** [comment]
inviata nc al fornitore con costo di gestione pari a Euro 60,00 (2 ore operatore + costo materiale)

**Comment by ELEONORANEW** [comment]
Realizzati degli spessori in piatto Al 60x5 L=100 con n. 2 fori interasse 76mm per fissaggio isolatori.
Gli spessore sono stati posizionati tra il longherone e la cappa inferiore di ciascun isolatore.
Sugli spessori in corrispondenza del golfare è stato realizzato uno scasso 65x20 per alloggio piatto golfare.
Montato il primo sezionatore e eseguita movimentazione.
A sezionatore aperto (tondino albero contro il fermo posto sulla spalla destra del telaio) la distanza tra coltello e contatto fisso superiore è 260mm quindi rispettata per tensione 24kV.

**Comment by nbianchinewmascherpa** [comment]
costo NC:
materiale + lavorazione: 125€
gestione: 50€
totale 175€
