### ISSUE TITLE
trasporto commessa 115.23 EDYNA

### ISSUE THREAD

**Issue by nbianchinewmascherpa** [nbianchinewmascherpa/Non-conformit-#64]
descrizione NC:

in fase di prenotazione spedizione, sono state indicate al corriere solo le dimensioni delle gabbie tralasciando i colli dei fasci

Causa:
mancanza di compilazione dati pesi/ingombri/colli da parte dell'operatore
inesperienza sui prodotti del reparto logistica.
prenotazione del trasporto prima dell'imballaggio effettivo.

risoluzione:
@ELEONORANEW  verificare con l'operatore che vengano compilati tutti i campi e le informazioni arrivino all'uff. logistica
@annalisa2023 verificare con la distinta la presenza di aste >1000 mm. in quel caso hai sempre il fascio di aste.

**Comment by nbianchinewmascherpa** [comment]
@annalisa2023 
compilare con tutti i costi sostenuti per la gestione del trasporto

**Comment by annalisa2023** [comment]
Costo spedizione con Bartolini n. 2 fasci lungh. 3 mt totale Euro 60,56. 
Ceccarelli non gestisce spedizioni di merce non pallettizzata. In definitiva nonostante l'errore in fase di prenotazione, la risoluzione si è rivelata la più economica.

**Comment by annalisa2023** [comment]
rif. ft. Bartolini 690027 del 31/10/23 Spedizione rif.550364-555053
