### ISSUE TITLE
Terminali destri dis. J1109_A comm.122.23 pezzi smarriti De Lucchi Spa

### ISSUE THREAD

**Issue by annalisa2023** [nbianchinewmascherpa/Non-conformit-#66]
n. 10 terminali dis. J1109_A consegnati a De Lucchi Spa con ddt 497 del 27.1.23 sono stati smarriti.

Commessa urgentissima. Pezzi riprodotti. riportati in saldatura. Bolla di lavorazione 23/988 - 23/989

riportati pezzi in De Lucchi con ddt 504. Scritto mail a fornitore .

Verranno riaddebitati i costi.

**Comment by nbianchinewmascherpa** [comment]
@annalisa2023  aggiornare NC con risposta de lucchi e costo riproduzione particolari nuovi.

**Comment by annalisa2023** [comment]
Costo riproduzione nuovi pezzi Euro 4,23  bolla 23/989
+ costo mat. fe

**Comment by nbianchinewmascherpa** [comment]
costo totale: 125€
