### ISSUE TITLE
ORDINE CMC 777.23 - COMM. 76.23 HI-PE

### ISSUE THREAD

**Issue by nbianchinewmascherpa** [nbianchinewmascherpa/Non-conformit-#67]
DESCRIZIONE NC:
- RIF. DISEGNO: CP2516: pezzi realizzati in materiale errato. i particolari dovevano essere in Al, ma sono stati realizzati in FE.
- RIF. DISEGNO: SU3371G: pezzi realizzati in materiale errato. i particolari dovevano essere in Al, ma sono stati realizzati in FE. il foro da 105 mm doveva essere in tolleranza H8 (105-105.054), ma da taglio risulta essere 105.10 mm. sul foro da 105 mm andava fatta la lamatura, che non è stata realizzata.

CAUSA NC:
- DISEGNO CP 2516: errore fornitore utilizzo materiale, sui disegni è indicato il materiale da utilizzare, inviate le specifiche in data 13/10/2023.
-  DISEGNO SU3371G: il laser non garantisce MAI i fori in tolleranza. @ELEONORANEW verifica che pre-foro fare per poi realizzare i fori in tolleranza. vanno realizzati 2 disegni: 1 per il laser + 1 per la lavorazione. La lamatura non è stata realizzata, in fase di offerta era stata inclusa? @annalisa2023  specificare sempre in offerta/ordine se ci sono esclusioni.

-RISOLUZIONE:
@nbianchinewmascherpa: inviare NC al fornitore;
@annalisa2023 verificare con Paolo se acquistando le punte possiamo fare il foro in tolleranza e la svasatura. altrimenti cercare un fornitore che faccia la lavorazione;
@ELEONORANEW sistemare i disegni con le due versioni.

**Comment by nbianchinewmascherpa** [comment]
inviata NC al fornitore in data 09/11/2023.
tutta la documentazione è salvata in: 
Z:\PRODUZIONE\NON CONFORMITA'\RNC 2023\67.23

**Comment by nbianchinewmascherpa** [comment]
@annalisa2023  aggiornare NC con costo punte e lavorazione omcf

**Comment by nbianchinewmascherpa** [comment]
particolari CP2516 _ SU3371G: rifatti da cmc con DDT 2147.
accordato totale per ordine 777.23: 900€.
@annalisa2023 aggiornare NC con costo TSM per saldatura del particolare CP2516

**Comment by nbianchinewmascherpa** [comment]
@annalisa2023 verificare ed aggiornare NC:
sconto CMC, costo punte e lavorazione svasatura e saldatura non eseguita da CMC ma fatta da TSM

**Comment by annalisa2023** [comment]
CMC riconosciuto sconto pari a Euro 70,00 per pezzi rifatti che non andavano rifatti (N.4 COPERCHIO ALLUMINIO
DIS.CP20151)

**Comment by annalisa2023** [comment]
Aggiornamento 20/03/24 RIF. DISEGNO: SU3371G
costo frese Utiemme Euro 190,00
costo lavorazione OMCF Euro 200,00
costo saldatura Tsm Euro 180,00

**Comment by nbianchinewmascherpa** [comment]
totale NC:
1400€
