### ISSUE TITLE
Blocchetto BL90004 - OMCF

### ISSUE THREAD

**Issue by annalisa2023** [nbianchinewmascherpa/Non-conformit-#69]
la profondità della cava è fuori tolleranza risulta essere 1.7

aorsani@newmascherpa.it  chiedere al fornitore se può riprendere i pezzi e portarli in tolleranza.

**Comment by annalisa2023** [comment]
Il fornitore conferma di aver sbagliato la programmazione macchina quindi riprodurrà i pezzi nuovamente consegnandoceli a suo carico domani 14/11/23

**Comment by nbianchinewmascherpa** [comment]
pezzi rifatti e consegnati dal fornitore in data 14/11/2023
