### ISSUE TITLE
NC FORNITURA RAITECH

### ISSUE THREAD

**Issue by nbianchinewmascherpa** [nbianchinewmascherpa/Non-conformit-#71]
rif. ordine fornitore 831.23:
- articolo U022 n. 5 pezzi: non presenti nel materiale fornito, ma inseriti in DDT n. 387/L
- articolo O10367: foro centrale da 90 mm fuori tolleranza. il foro realizzato risulta essere da 89.6 mm.
- articolo 10172: fornito in Fe anzichè in Peraluman come da disegno.

rif. ordine fornitore 815.23:
- articolo O10320_B1: quota interna di piegatura a 41 mm invece che 45 mm; foro centrale da 33.5 mm invece che 34 mm. la foratura risulta anche spanciata dalla piega.
- articolo U126_A: foro centrale da 45.8 mm invece che 46+0.1+0.25 come da disegno.
- articolo U114: saldatura errata del particolare U114_D: è stato saldato superiormente anzichè inferiormente.
- articolo U114_D: foratura centrale da 94.7 mm. tolleranza a disegno 95 +0.1 +0.25 mm.
- articolo U115: la piastra in piegatura ha subito una torsione. gli interassi dei fori di fissaggio risultano diversi tra loro.

tutto il materiale sopra indicato non può essere accettato e deve essere riprodotto con massima urgenza.

i codici seguenti, nonostante NC rilevate, verranno accettati in deroga:
-articolo U126_C: foro centrale da 48.25 mm invece che 48.5 mm;
-articolo O10311_D: fori da 18 mm realizzati da 20 mm.

**Comment by nbianchinewmascherpa** [comment]
![WhatsApp Image 2023-11-17 at 16 59 24 (1)](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/115451135/7f963cd1-ab97-423d-8cae-33d5acc93ddf)
![WhatsApp Image 2023-11-17 at 16 59 24](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/115451135/65e5a65f-ce7c-44af-b1e6-5fb47b03324c)
![WhatsApp Image 2023-11-17 at 16 59 25 (1)](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/115451135/bda0f75e-2f9a-4788-ae2d-4e54bf22f31e)
![WhatsApp Image 2023-11-17 at 16 59 25](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/115451135/48c3e784-a375-404e-9fba-76bbcc75cfa9)
![WhatsApp Image 2023-11-17 at 16 59 26 (1)](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/115451135/008660ce-3336-4c2f-bd13-e467f37f7b1d)
![WhatsApp Image 2023-11-17 at 16 59 26](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/115451135/d7c55b0c-81c7-4f0b-bd56-ed72d822d698)
![WhatsApp Image 2023-11-17 at 16 59 27 (1)](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/115451135/b79601db-c2c2-4ac8-b67b-2c6a5fb63d6b)
![WhatsApp Image 2023-11-17 at 16 59 27](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/115451135/97869984-9dc7-43c0-b6ad-4b6aefcce2b9)
![WhatsApp Image 2023-11-17 at 16 59 23 (1)](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/115451135/0e05df09-9ac4-464e-835a-b95c4e885551)
![WhatsApp Image 2023-11-17 at 16 59 23 (2)](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/115451135/27b1631b-5b63-473a-a00d-dfb673722744)
![WhatsApp Image 2023-11-17 at 16 59 23](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/115451135/06cdf83d-b86d-4659-9a6f-4f3f1e4cf2d1)

**Comment by nbianchinewmascherpa** [comment]
@annalisa2023 
INVIARE NC AL FORNITORE. CHIEDERE RIPRODUZIONE NEL MINOR TEMPO POSSIBILE. FOTO SALVATE IN:
Z:\PRODUZIONE\NON CONFORMITA'\RNC 2023\RAITECH
AVVISA @ELEONORANEW  DATA DI CONSEGNA PEZZI RIFATTI.

**Comment by annalisa2023** [comment]
28/11/2023 Arrivati i seguenti pezzi in sostituzione in garanzia (ddt 410/L del 22/11/23):
U126_A
U114
U115
U022
U116_A
