### ISSUE TITLE
CASSSETTA MANOVRA COMM. 88.23 - ORDINE 803.23 EIQ

### ISSUE THREAD

**Issue by nbianchinewmascherpa** [nbianchinewmascherpa/Non-conformit-#72]
DESCRIZIONE NC:
la cassetta ha una larghezza totale di 700 mm invece che 750 mm, come indicato nel ns. ordine e nella descrizione del codice disegno del fornitore. in fase di invio del disegno da parte del fornitore la cassetta aveva una larghezza di 700 mm. tale differenza non è stata individuata nel nostro controllo disegno.

!!VERIFICARE CON MAGGIORE ATTENZIONE I DOCUMENTI INVIATI DAI FORNITORI.

RISOLUZIONE:
- @annalisa2023  INVIARE NC AL FORNITORE
- @ELEONORANEW verificare se la cassetta non conforme possa essere utilizzata lo stesso.
- @nbianchinewmascherpa @annalisa2023  comunicare ad EIQ costi per l'adattamento della cassetta NC e richiedere sconto su questa fornitura.

**Comment by nbianchinewmascherpa** [comment]
@annalisa2023 inviare costo della NC al fornitore per un totale di 115€.
vedere Bolle di lavorazione 1238-1239-1241.

**Comment by annalisa2023** [comment]
Chiamato Sig.ra Daiana e inviato mail comunicando costo NC e chiedendo nota credito a storno ft. 2841

**Comment by nbianchinewmascherpa** [comment]
emessa nota di credito in data 14/03/2024 - n. 721.
