### ISSUE TITLE
ORDINE ETA DRIVEUNITS 800.23

### ISSUE THREAD

**Issue by nbianchinewmascherpa** [nbianchinewmascherpa/Non-conformit-#74]
Descrizione NC:

1) il particolare dis. K10471 presenta la foratura d. 6 mm a 16.5 mm invece che a 15 mm. 
2) il particolare dis. K10472 presenta le fresature da 15 mm invece che da 10 mm.
3) su tutti i codici il foro centrale da 16 mm, è stato realizzato da 15.4-15.6 mm con conicità.

Risoluzione NC:
punti 1) - 2) accettati con deroga
punto 3) ripassate le forature internamente per poter eseguire accoppiamento con l'albero.

@annalisa2023  inviare NC al fornitore. chiedere sconto per la rilavorazione interna (16€ rilavorazione + 15 € gestione)

**Comment by annalisa2023** [comment]
13/12/2023 Il fornitore accorda lo sconto richiesto

**Comment by annalisa2023** [comment]
emessa n.c. 4 del 19/12/23 solo per i 15 Euro. Chiesto aggiunta dei 15,00 euro

**Comment by annalisa2023** [comment]
emessa n.c. 5 del 19/12/23 per i 16 Euro
