### ISSUE TITLE
ORDINE CMC - 898.23

### ISSUE THREAD

**Issue by nbianchinewmascherpa** [nbianchinewmascherpa/Non-conformit-#75]
descrizione NC:

- particolare PP 101216: il particolare è stato realizzato con lunghezza 58 mm invece che 70 mm;
- particolare PP 101215: il particolare è stato realizzato con lunghezza 70 mm invece che 58 mm;
- particolari PA 50478 - PA 50480: le fresature dovevano essere opposte alla foratura, invece sono state realizzate sullo stesso asse.

Causa: 
disegni reimpostati dal fornitore con emissione errata

Risoluzione:
inviare NC al fornitore e chiedere la rimessa in produzione.

**Comment by nbianchinewmascherpa** [comment]
inviata mail in data 13/12/2023 al fornitore.
![WhatsApp Image 2023-12-12 at 17 06 24 (1)](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/115451135/27b11c11-f6af-49b1-a5eb-f7a5c0409a07)
![WhatsApp Image 2023-12-12 at 17 06 24](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/115451135/967314fa-da63-477e-a7a8-96e9c5139b2c)
![WhatsApp Image 2023-12-12 at 17 06 24 (3)](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/115451135/2347584a-da3a-42d6-8d2b-961d26cd84fa)
![WhatsApp Image 2023-12-12 at 17 06 24 (2)](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/115451135/5fc416ec-b464-45bb-9a14-a2aedd1bc79c)
[PP 10216 - PIASTRINA.pdf](https://github.com/nbianchinewmascherpa/Non-conformit-/files/13661057/PP.10216.-.PIASTRINA.pdf)
[PP 10215 - PIASTRINA.pdf](https://github.com/nbianchinewmascherpa/Non-conformit-/files/13661058/PP.10215.-.PIASTRINA.pdf)
[PA 50478 - CASSA.pdf](https://github.com/nbianchinewmascherpa/Non-conformit-/files/13661059/PA.50478.-.CASSA.pdf)
[PA 50480 - CASSA.pdf](https://github.com/nbianchinewmascherpa/Non-conformit-/files/13661060/PA.50480.-.CASSA.pdf)

**Comment by annalisa2023** [comment]
13/12/2023 pezzi riprodotti conformi (consegnati con ddt 2432 del 14/12/23)
