### ISSUE TITLE
ordine 893.23+927.23 RAITECH

### ISSUE THREAD

**Issue by nbianchinewmascherpa** [nbianchinewmascherpa/Non-conformit-#76]
Descrizione NC:
1) disegno 010256: piastre realizzate con sp. 6 mm invece che 10 mm;
2) disegno C10041: larghezza telaio 211 mm invece che 212 mm, quindi risulta fuori di 1 mm l'interasse tra i fori (175 mm invece che 176 mm). Manca foro da 13 mm sul lato del telaio.

Causa: 
1) utilizzo errato del materiale da parte del fornitore
2) macchine con tolleranze maggiori di quelle richieste? la foratura risulta mancante, perchè il foro nello sviluppo non è stato inserito e il fornitore non lo ha considerato.

Risoluzione:

1) @annalisa2023  chiedere al fornitore di rifare le piastre con lo spessore corretto e di gestire la spedizione a sue spese. Particolari urgentissimi.
2) particolare accettato. @ELEONORANEW sistemare il disegno aggiungendo il foro anche nello sviluppo. creare una bolla di lavorazione per eseguire la foratura. @annalisa2023 inserire il costo di lavorazione nella chiusura della NC.

**Comment by nbianchinewmascherpa** [comment]
2) sistemato il telaio con la foratura mancante in data 13/12/2023. tempo di lavorazione 10 min.

**Comment by annalisa2023** [comment]
18/12/2023 Pezzi rifatti arrivati con ddt 24/I del 13/12/23

costo finale non conformità 25,00 Euro

**Comment by annalisa2023** [comment]
Applicato sconto sul ft. 54 del 26/03/24
