### ISSUE TITLE
ORDINE 838.23 ETA DRIVE UNITS

### ISSUE THREAD

**Issue by nbianchinewmascherpa** [nbianchinewmascherpa/Non-conformit-#77]
Descrizione NC:

1) particolare K10470: raggiatura diversa da campione inviato. A disegno non risulta indicata la quota per la raggiatura. presenza di segni sulla superficie dei pezzi. 
2) dis. K10469:
- i pernetti risultano spostati di 2.5 mm (invece che 9 mm risultano a 11.5 mm);
- lo scasso da 38 mm risulta fuori tolleranza (scarso di 0.5 mm)
- foratura M6 realizzata come da campione. Disegno errato da sistemare.

Risoluzione:
1) eseguita raggiatura internamente per aumentare l'invito. 75 € lavorazioni interne. Verificare nota da inserire a disegno per la finitura superficiale dei pezzi. Se non è possibile rilevare la quota della raggiatura, inserire nota a disegno per il fornitore, di rispettare le quote dei campioni inviati. inserire sempre la nota anche nell'ordine di acquisto;
2) accettate variazioni di quota in deroga.

@ELEONORANEW  sistemare disegno per posizioni forature M6 e note sulla raggiatura.

@annalisa2023 inviare costo NC al fornitore.

**Comment by nbianchinewmascherpa** [comment]
![WhatsApp Image 2023-12-15 at 14 23 44 (2)](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/115451135/6a26d88c-9bcd-4ec8-b167-7dd3cc3c02b2)
![WhatsApp Image 2023-12-15 at 14 23 44 (1)](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/115451135/22210f4a-53b8-4d3f-9945-b77ed634622d)
![WhatsApp Image 2023-12-15 at 14 23 44](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/115451135/ad648383-b542-4310-ac55-dd2559ded153)
![WhatsApp Image 2023-12-15 at 13 55 04](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/115451135/91066ff2-46ec-4bf2-956e-d327e037ac0e)

**Comment by ELEONORANEW** [comment]
dis. K10469: modificata la posizione dei fori.
dis. K10470: non è possibile indicare la quota di raggiatura sul disegno perchè non abbiamo strumenti adatti a rilevare tale quota.
Paolo ha raccordato i pezzi sul tornio parallelo con l'utensile solitamente utilizzato per la realizzazione della sfericità r=8 dei particolari AT3005/1 e AT3004.

**Comment by annalisa2023** [comment]
Eta Drive Units emesso Nota Credito n. 4 del 19/12/23

**Comment by annalisa2023** [comment]
Ulteriore NC su pezzi K10469
![Immagine WhatsApp 2023-12-22 ore 09 28 17_812ce877](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/122519971/9ff0f0b1-8260-4a12-9035-bc8da41db1ed)
![Immagine WhatsApp 2023-12-22 ore 09 28 23_2a265a24](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/122519971/b248b554-36e4-404d-a129-a168710d122f)

i due perni risultano in posizione errata
si provvederà alla sistemazione con addebito a Eta di Euro 50,00

**Comment by annalisa2023** [comment]
Eta emessa nota credito n. 4 del 19/12/23 per Euro 75,00
