### ISSUE TITLE
NON CONFORMITA' GABBIA PER DY 595 - dis. 596/33 - ORDINE CAM 215/24

### ISSUE THREAD

**Issue by ELEONORANEW** [nbianchinewmascherpa/Non-conformit-#78]
Non conformità su 4 gabbie dis. 596/33 rif. ns. ordine 215/24.
I due spessori da 8 (evidenziati in verde) sono stati fissati sul lato opposto a quello indicato a disegno.
![image](https://github.com/nbianchinewmascherpa/Non-conformit-/assets/122519843/a4620316-28f9-49f8-aeaa-3bd731077a7f)

Inviata e-mail con richiesta di intervento immediato per la sistemazione delle gabbie non conformi.

**Comment by annalisa2023** [comment]
rese le n.4 gabbie dis. 596/33 (ns.ddt. 178 del 09.04.24) per sistemazione

**Comment by annalisa2023** [comment]
Gabbie rese sistemate ddt a/612 del 09/04/24
In realtà erano solo 3 i pezzi non conformi
