### ISSUE TITLE
NON CONFORMITA' GABBIA PER DY 595 - dis. 596/33 - ORDINE CAM 215/24

### ISSUE THREAD

**Issue by ELEONORANEW** [nbianchinewmascherpa/Non-conformit-#79]
Riscontrato non conformità sulle gabbie consegnate sempre relative al tipo 596/33.

-	I piedi (particolare 3) sono larghi 75mm anziché 70mm. Inoltre sono lunghi 760mm anziché 755mm.
-	La traversa bassa lato golfare (particolare 5) è larga 75mm anziché 80mm
Le non conformità indicate sopra non permettono un corretto alloggiamento del sezionatore nella gabbia, causando un possibile spostamento di questo all’interno della gabbia durante il trasporto.

-	Alcune gabbie hanno una larghezza interna minore (probabilmente dovuto ad un assemblaggio non corretto) e ciò non permette l’inserimento del sezionatore nella gabbia.

Richiesto un nuovo incontro con geometra Matteo Mauri c/o ns. sede per verificare tutte le non conformità riscontrate.

**Comment by ELEONORANEW** [comment]
9/4/24: telefonata con geom. Matteo Mauri.
Per la commessa 25/24 teniamo le gabbie così come sono (eccetto quelle non conformi che ci sistemano (vedi non conformità #78)

Le dimensioni dei vari particolari indicati a disegno non sono dimensioni std da commercio.
Al momento stanno realizzando le gabbie con dimensioni diverse rispetto a quanto indicato sul ns. disegno.

Per prossime forniture:
appena monteremo il sezionatore della commessa 55/24, lo porteremo alla Cam in modo che realizzeranno gabbie ad hoc per i ns. sezionatori DY595 in modo da non avere più problemi per prossimi imballaggi.

@annalisa2023 appena Lorenzo avrà montato il DY595 della commessa 55/24 - (bolla 24/00719)
chiamare Cam per ritiro.
Chiedere disegno appena realizzeranno il prototipo.

**Comment by annalisa2023** [comment]
10/04/2024 ddt 181/24 consegnato sezionatore in conto visione per costruzione gabbia

**Comment by annalisa2023** [comment]
18/04/2024 consegnata nuova gabbia 595 con ddt A/0683
